name: Publish website to cpanel
on:
  push:
    branches:
      - main
jobs:
    FTP-Deploy-Action:
      name: FTP-Depoly-Action
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: samkirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ sercrets.FTP_PASSWORD }}
